package com.example.animeapp2.enums

enum class GenreEnum(val genreNumber : Int) {
    Action(1),
    Adventure(2),
    Cars(3),
    Comedy(4),
    Avante_Garde(5),
    Demons(6),
    Mystery(7),
    Drama(8),
    Ecchi(9),
    Fantasy(10),
    Game(11),
    Hentai(12),
    Historical(13),
    Horror(14),
    Kids(15),
    Martial_Arts(17),
    Mecha(18),
    Music(19),
    Parody(20),
    Samurai(21),
    Romance(22),
    School(23),
    Sci_Fi(24),
    Shoujo(25),
    Girls_Love(26),
    Shounen(27),
    Boys_Love(28),
    Space(29),
    Sports(30),
    Super_Power(31),
    Vampire(32),
    Harem(35),
    Slice_Of_Life(36),
    Supernatural(37),
    Military(38),
    Police(39),
    Psychological(40),
    Suspense(41),
    Seinen(42)

}